//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peoples
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Old { get; set; }
        public int Cities_Id { get; set; }
    
        public virtual Sities Sities { get; set; }
    }
}
