//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication87.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Orders = new HashSet<Orders>();
        }

        [Display(Name = "ИД продукта")]
        public int ProductId { get; set; }

        [Display(Name = "Наименование товара")]
        public string ProductName { get; set; }

        [Display(Name = "Цена товара")]
        public decimal ProductPrice { get; set; }

        [Display(Name = "Описание товара")]
        public string ProductDescription { get; set; }

        [Display(Name = "Дата добавления товара")]
        [DataType(DataType.Date)]
        public System.DateTime ProductDateAdd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
