//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication87.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Orders = new HashSet<Orders>();
        }

        [Display(Name = "ИД пользователя")]
        public int UserId { get; set; }

        [Display(Name = "Имя пользователя")]
        public string UserFirstName { get; set; }

        [Display(Name = "Фамилия пользователя")]
        public string UserLastName { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Дата регистрации пользователя")]
        public System.DateTime UserDateRegister { get; set; }

        [Display(Name = "Почта")]
        [DataType(DataType.EmailAddress)]
        public string UserEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
